# Generated by Django 6.0.2 on 2026-03-24 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('metodopago', models.CharField(blank=True, db_column='metodoPago', max_length=50, null=True)),
                ('numerofactura', models.CharField(blank=True, db_column='numeroFactura', max_length=50, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'carrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('idproducto', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('stocktotal', models.IntegerField(blank=True, db_column='stockTotal', null=True)),
                ('costouni', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('capacidad_maxima', models.IntegerField()),
                ('alerta_minimos', models.IntegerField()),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('ultima_revision', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('usuario_ultima_actualizacion', models.BigIntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombrepermiso', models.CharField(db_column='nombrePermiso', max_length=50)),
            ],
            options={
                'db_table': 'permiso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('nit', models.CharField(blank=True, max_length=255, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, max_length=255, null=True)),
                ('nombrerol', models.CharField(blank=True, db_column='nombreRol', max_length=255, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('id_inventario', models.ForeignKey(db_column='id_inventario', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.inventario')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('nombre_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='gestion.pedido')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
            options={
                'verbose_name': 'Detalle del Pedido',
                'verbose_name_plural': 'Detalles de los Pedidos',
                'db_table': 'detalle_pedido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Detallecarrito',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.carrito')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.producto')),
            ],
            options={
                'db_table': 'detallecarrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id_promocion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_incio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(max_length=255)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.producto')),
            ],
            options={
                'db_table': 'promocion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id_rol_permisorol', models.IntegerField(primary_key=True, serialize=False)),
                ('id_rol', models.ForeignKey(db_column='id_Rol', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.rol')),
                ('idpermiso', models.ForeignKey(db_column='idPermiso', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.permiso')),
            ],
            options={
                'db_table': 'rol_permiso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='contraseña', max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_identificacion', models.CharField(blank=True, db_column='tipo_identificacion', max_length=255, null=True)),
                ('numero_identificacion', models.CharField(blank=True, db_column='numero_identificacion', max_length=255, null=True)),
                ('es_activo', models.BooleanField(db_column='es_activo', default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='gestion.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pqrsf',
            fields=[
                ('id_pqrsf', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('leida', models.TextField()),
                ('id_carrito', models.ForeignKey(blank=True, db_column='id_carrito', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.carrito')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.usuario')),
            ],
            options={
                'db_table': 'pqrsf',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario'),
        ),
        migrations.CreateModel(
            name='Ordencompra',
            fields=[
                ('id_orden', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.proveedor')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.usuario')),
            ],
            options={
                'db_table': 'ordencompra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fechaenvio', models.DateTimeField(auto_now_add=True, db_column='fechaEnvio', null=True)),
                ('carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, to='gestion.carrito')),
                ('pqrsf', models.ForeignKey(blank=True, db_column='id_pqrsf', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.pqrsf')),
                ('usuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(max_length=7)),
                ('cantidad', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_inventario', models.ForeignKey(db_column='id_inventario', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.inventario')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.usuario')),
            ],
            options={
                'db_table': 'movimientos_inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialUsuario',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('campomodificado', models.CharField(blank=True, db_column='campoModificado', max_length=50, null=True)),
                ('valoranterior', models.TextField(blank=True, db_column='valorAnterior', null=True)),
                ('valornuevo', models.TextField(blank=True, db_column='valorNuevo', null=True)),
                ('fechacambio', models.DateTimeField(db_column='fechaCambio')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.usuario')),
            ],
            options={
                'db_table': 'historial_usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fidelizacion',
            fields=[
                ('idfidelizacion', models.AutoField(db_column='idFidelizacion', primary_key=True, serialize=False)),
                ('puntos', models.IntegerField(blank=True, null=True)),
                ('nivel', models.CharField(blank=True, max_length=30, null=True)),
                ('idusuario', models.ForeignKey(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.usuario')),
            ],
            options={
                'db_table': 'fidelizacion',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('puntuacion', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, to='gestion.carrito')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'calificacion',
                'managed': True,
            },
        ),
    ]
