# Generated by Django 6.0.2 on 2026-03-26 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pqrsf',
            name='id_carrito',
        ),
        migrations.RemoveField(
            model_name='pqrsf',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
        migrations.DeleteModel(
            name='Pqrsf',
        ),
    ]
