# Generated by Django 6.0.2 on 2026-04-05 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_pqrsf_id_carrito_remove_pqrsf_id_usuario_and_more'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='id_proveedor',
            field=models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.DO_NOTHING, to='proveedor.proveedor'),
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrito',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detallecarrito',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='estado',
            field=models.CharField(blank=True, choices=[('abierto', 'Abierto'), ('pendiente_pago', 'Pendiente de pago'), ('pagado', 'Pagado'), ('pendiente_entrega', 'Pendiente de entrega'), ('entregado', 'Entregado')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
