# Generated by Django 6.0.2 on 2026-04-06 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_ordencompra_id_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRestablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario')),
            ],
            options={
                'verbose_name': 'Token de Restablecimiento',
                'db_table': 'token_restablecimiento',
            },
        ),
    ]
