# Generated by Django 6.0.2 on 2026-04-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_tokenrestablecimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda_abierta', models.BooleanField(default=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.usuario')),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'db_table': 'configuracion_tienda',
            },
        ),
    ]
