# Generated by Django 6.0.2 on 2026-04-02 00:59

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('idproducto', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('stocktotal', models.IntegerField(blank=True, db_column='stockTotal', null=True)),
                ('costouni', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('capacidad_maxima', models.IntegerField()),
                ('alerta_minimos', models.IntegerField()),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('ultima_revision', models.DateField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('usuario_ultima_actualizacion', models.BigIntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioDiario',
            fields=[
                ('id_inventario_diario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('realizado_por', models.IntegerField()),
                ('nombre_responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('total_productos', models.IntegerField(default=0)),
                ('total_diferencias', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'inventario_diario',
                'ordering': ['-fecha', '-create_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleInventarioDiario',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_anterior', models.IntegerField(default=0)),
                ('stock_fisico', models.IntegerField(default=0)),
                ('diferencia', models.IntegerField(default=0)),
                ('alerta_minimos', models.IntegerField(default=5)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=50, null=True)),
                ('inventario_diario', models.ForeignKey(db_column='id_inventario_diario', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.inventariodiario')),
            ],
            options={
                'db_table': 'detalle_inventario_diario',
                'managed': True,
            },
        ),
    ]
