from django.urls import path
from . import views

urlpatterns = [
    path('',                                       views.catalogo_view,       name='catalogo'),
    path('agregar/<int:id_producto>/',             views.agregar_carrito,     name='agregar_carrito'),
    path('carrito/',                               views.ver_carrito,         name='ver_carrito'),
    path('carrito/actualizar/<int:id_detalle>/',   views.actualizar_cantidad, name='actualizar_cantidad'),
    path('carrito/eliminar/<int:id_detalle>/',     views.eliminar_detalle,    name='eliminar_detalle'),
    path('carrito/contador/',                      views.contador_carrito,    name='contador_carrito'),
    path('carrito/confirmar/',                     views.confirmar_pedido,    name='confirmar_pedido'),
    path('pedido-confirmado/',                     views.pedido_confirmado,   name='pedido_confirmado'),
    path('pedidos/',                               views.vista_vendedor,      name='vista_vendedor'),
    path('pedidos/pagar/<int:id_carrito>/',        views.registrar_pago,      name='registrar_pago'),
    path('pedidos/entregar/<int:id_carrito>/',     views.confirmar_entrega,   name='confirmar_entrega'),
    path('pedidos/json/', views.pedidos_json, name='pedidos_json'),
    path('pedidos/cobrar/<int:id_carrito>/', views.cobrar_pedido, name='cobrar_pedido'),
    path('cajero/',                    views.vista_cajero,       name='vista_cajero'),
    path('cajero/agregar/',            views.cajero_agregar_item, name='cajero_agregar_item'),
    path('cajero/buscar-cliente/',     views.buscar_cliente,      name='buscar_cliente'),
    path('cajero/crear-cliente/', views.cajero_crear_cliente_rapido, name='cajero_crear_cliente_rapido'),
    path('tienda/estado/', views.estado_tienda_json, name='estado_tienda_json'),
    path('pedidos/cobrar-nequi/<int:id_carrito>/', views.cobrar_nequi, name='cobrar_nequi'),
    path('pago/nequi/<int:id_carrito>/',          views.pago_nequi_cliente,   name='pago_nequi_cliente'),
    path('pago/nequi/confirmar/<int:id_carrito>/', views.confirmar_pago_nequi, name='confirmar_pago_nequi'),
    path('pago/daviplata/<int:id_carrito>/',          views.pago_daviplata_cliente,   name='pago_daviplata_cliente'),
    path('pago/daviplata/confirmar/<int:id_carrito>/', views.confirmar_pago_daviplata, name='confirmar_pago_daviplata'),
    path('historial/', views.historial_cliente, name='historial_cliente'),
    path('calificar/<int:id_carrito>/', views.calificar_pedido, name='calificar_pedido'),
    path('calificar/guardar/<int:id_carrito>/', views.guardar_calificacion, name='guardar_calificacion'),
    path('pedido/<int:id_carrito>/', views.detalle_pedido, name='detalle_pedido'),
]