# Generated by Django 6.0.6 on 2026-06-10 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='pqrsf',
            field=models.ForeignKey(blank=True, db_column='pqrsf_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pqrs.pqrsf'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('pqrsf', 'PQRSF'), ('carrito', 'Carrito / Pedido'), ('sistema', 'Sistema'), ('stock', 'Stock bajo')], default='sistema', max_length=20),
        ),
    ]
