# Generated by Django 6.0.2 on 2026-03-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PQRSF',
            fields=[
                ('id_pqrsf', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Petición', 'Petición'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia'), ('Felicitación', 'Felicitación')], max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Leída', 'Leída'), ('En gestión', 'En gestión'), ('Resuelta', 'Resuelta'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=20)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PQRSF',
                'verbose_name_plural': 'PQRSFs',
                'db_table': 'pqrsf',
                'managed': False,
            },
        ),
    ]
